steps:
# Step 1: Set up SSH directory and key
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p ~/.ssh && 
    gcloud secrets versions access latest --secret=cloud-build-ssh-key > ~/.ssh/id_rsa &&
    echo ~/.ssh/id_rsa &&
    chmod 600 ~/.ssh/id_rsa &&
    ssh-keyscan -H 34.44.98.81 >> ~/.ssh/known_hosts

# Step 2: Deploy to Compute Engine VM
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no bhargavyagnik99@34.44.98.81 \
    'cd ~/styl && \
    git fetch --all && \
    git reset --hard origin/main && \
    (docker compose down || true) && \
    (docker system prune -af --volumes || true) && \
    (docker volume ls -qf dangling=true | xargs -r docker volume rm || true) && \
    docker compose up -d --build'

options:
  logging: CLOUD_LOGGING_ONLY