steps:
# Step 1: Pull the latest changes from the GitHub repository
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'instance-20240817-002533'
  - '--zone=us-central1-c'
  - '--command=cd ~/styl && git pull && docker compose down && docker system prune && docker volume rm $(docker volume ls -qf dangling=true | xargs) && docker compose up -d --build'
options:
  logging: CLOUD_LOGGING_ONLY